os: osx
osx_image: xcode12.2
language: swift

xcode_project: AWeather.xcodeproj

matrix:
  include:
    - xcode_scheme: CI-IOS
      xcode_sdk: iphonesimulator13.0

    - xcode_scheme: CI
      xcode_sdk: macosx11.0